# NumPy  
  
Es una librería para trabajar con vectores y matrices multidimensionales, con una colección de funciones matemáticas
poderosas.  
  
Su estructura de datos fundamental es *ndarray* que permite configurar una matriz de *n* dimensiones. La matriz debe ser homogénea.

## Instalación

pip install numpy

## Creación de un ndarray

np.array(*secuencia*)

In [6]:
import numpy as np
vec=np.array([2,4,8,3])
print(vec)
print(type(vec))
print(vec.dtype) # tipo de dato que almacena el array
vec=np.array([1.2,3,5.4])
print(vec.dtype)

[2 4 8 3]
<class 'numpy.ndarray'>
int32
float64


Transforma secuencias de secuencias en un array de 2 dimensiones, secuencias de secuencias de secuencias en uno de 3 y así sucesivamente:

In [8]:
dosD=np.array([[1,4,2], [4,5,3]])
print(dosD)
tresD=np.array((((1,2),(4,3),(5,3)),((8,9),(2,6),(2,1))))
print(tresD)

[[1 4 2]
 [4 5 3]]
[[[1 2]
  [4 3]
  [5 3]]

 [[8 9]
  [2 6]
  [2 1]]]


Podemos declarar el tipo en su constructor:

In [10]:
complejo=np.array([1,5,2,3], dtype="complex")
print(complejo)
flotante=np.array([1,5,2,3], dtype="float64")
print(flotante)

[1.+0.j 5.+0.j 2.+0.j 3.+0.j]
[1. 5. 2. 3.]
